// GENERATED by src/scripts/build/gen-signing-key.ts
// Commit this file. Do NOT commit signing-private.key.
export const TRUSTED_PUBKEY_B64 = 'g9WJiFXfFlekSxhRsmUP2MqqY2AlasbRw/R761EDYAc=';
export const TRUSTED_PUBKEY_FINGERPRINT = 'ed25519:83d5898855df1657';
