/*
 * Pins the baked production signing pubkey. If either value changes, this
 * test fails loudly — the developer must confirm the change is intentional.
 *
 * Why this matters: commit 09a3b163 (unrelated UI change) silently
 * overwrote this file with an ephemeral test key generated by a scratch
 * script. Every signed probe from v0.18.0 → v0.18.2 therefore returned
 * `invalid-signature`, so the auto-update popup never appeared in prod.
 *
 * If this test fails:
 *   1. Legitimate key rotation → update the values here AND the
 *      UPDATE_SIGNING_KEY GitHub Actions secret in the same PR.
 *   2. Accidental test-key commit → revert the change to
 *      trusted-pubkey.generated.ts.
 */
import {describe, it, expect} from 'vitest';
import {TRUSTED_PUBKEY_B64, TRUSTED_PUBKEY_FINGERPRINT} from '@lib/update/signing/trusted-pubkey.generated';

describe('trusted pubkey pin (production baseline)', () => {
  it('TRUSTED_PUBKEY_B64 matches the production signing key', () => {
    expect(TRUSTED_PUBKEY_B64).toBe('g9WJiFXfFlekSxhRsmUP2MqqY2AlasbRw/R761EDYAc=');
  });

  it('TRUSTED_PUBKEY_FINGERPRINT matches the production signing fingerprint', () => {
    expect(TRUSTED_PUBKEY_FINGERPRINT).toBe('ed25519:83d5898855df1657');
  });
});
